;ESTABLECER MODO VIDEO
MOV AH, 00H
MOV AL, 02H
INT 10H

;LIMPIAR PANTALLA
MOV AH,06H
MOV AL, 0;LIMPIAR PANTALLA
MOV BH, 0FFH;ATRIBUTO DEL COLOR DEL FONDO
MOV CX,00;INICIALIZAR RENG,COL
MOV DL,79;COL FINAL
MOV DH,24;RENG FINAL
INT 10H


;COLOCAR EL CURSOR
MOV AH,02H
MOV BH,0;PAGINA ACTUAL
MOV DX, 12
MOV DL, 10
INT 10H

;ESCRIBIR MI MSG 
MOV AH,09H
MOV DX, OFFSET MSG
INT 21H

INT 20H;FIN DEL PROGRAMA

MSG DB "HOLA MUNDO" 