VALOR DB 0  ;INICIALIZAMOS LA VARIABLE VALOR
INICIO:
        MOV AX,100  ;SE ASIGNA 100 EN EL ARREGLO MAX  
        MOV VALOR,2 ;EL 2 A LA VARIABLE VALOR
        MOV BH,0    ;ASIGNANMOS AL REGISTRO BASE
        MOV CL,1    ;ASIGNAMOS AL REGISTRO CONTADOR              
OTRO:   CMP CL,14H ;COMPARACION ENTRE EL REGISTRO 
        JZ SALIR   ;SI SON IGUALES SALDRA
        ;SI LOS VALORES NO SON IGUALES SE REALIZA LO SIGUIENTE  
        ADD BH,VALOR   ;BH=BH+VALOR SE SUMAN
        INC CL ;CL=CL+1
        JMP OTRO   ;REGRESA A LA LINEA 00
SALIR:  INT 20H  ;JZ LLEGARA AQUI Y SE IMRPIMIRA EL MENSAJE 

            