.model small
.stack 
.data 
MSG DB "PROGRAMA QUE MUESTRA EL VECTOR DE INTERRUPCIONES:",10,13,"$"
.code 

MOV AX,@DATA
MOV DS,AX
MOV AH,09
LEA DX,MSG      ;IMPRIME EL MENSAJE DE INICIO
INT 21H

MOV AX, 0  
MOV DS, AX    
MOV SI,0        ;INICIALIZAMOS LOS VALORES
MOV CX,10H 

START: 
MOV AX,[SI]  
PUSH AX     ;MOVEMOS EL VALOR DEL PUNTERO 
MOV DL,AH   
CALL IMP ;LLAMAMOS A LA FUNCION QUE IMPRIME 2 DIGITOS

POP AX
MOV DL,AL   ;RECUPERAMOS EL VALOR DE LA PILA
CALL IMP    ;LLAMAMOS A LA FUNCION QUE IMPRIME 2 DIGITOS

INC SI 
INC SI ;INCREMENTAMOS EL VALOR DEL PUNTERO
MOV DL,":"
MOV AH,02H  
INT 21H    

MOV AX,[SI]    ;SE REPITE EL PROCESO 
PUSH AX        
MOV DL,AH      
CALL IMP 

POP AX         
MOV DL,AL      
CALL IMP 

INC SI         
INC SI
MOV DL,0AH 
MOV AH,02H 
INT 21H  
       ;HACEMOS UN SALTO
MOV DL,0DH 
MOV AH,02H
INT 21H  

LOOP START ;HACEMOS UN LOOP EN LA FUNCION START
MOV AH,00H  
INT 21H     ;TERMINAMOS LA EJECUCION
IMP:
PUSH DX  
SHR DL,4H  ;OBTENEMOS EL VALOR DE LA PILA Y HACEMOS EL DEZPLAZAMIENTO 
CMP DL,09H 
JG T        ;COMPARAMOS EL VALOR CON 9 Y VAMOS A LA FUNCION T

ADD DL,30H ;SUMAMOS PARA OBTENER EL DIGITO
MOV AH,02H
INT 21h
E:              
POP DX     
AND DL,0FH 
CMP DL,09H ;RECUPERAMOS EL VALOR DE LA PILA Y EL EL RESTO DEL RESULTADO
JG S        ;SALTA LA FUNCION S
ADD DL,30H  ;OBTENEMOS EL DIGITO
MOV AH,02H 
INT 21H    
RET        ;REGRESAMOS A IMP
T: 
ADD DL,37H ;SUMAMOS 37H Y OBTENEMOS LA LETRA
MOV AH,02H 
INT 21H    ;IMPRIMIMOS 
JMP E     ;SALTAMOS A E
        
S: 
ADD DL,37H 
MOV AH,02H ;HACEMOS LO MISMO QUE EN T PERO RETORNAMOS A IMP
INT 21H    
RET            

END